version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: xai_tech_postgres
    environment:
      POSTGRES_DB: xai_tech
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  loki:
    image: grafana/loki:2.9.0
    container_name: xai_tech_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./grafana/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.0
    container_name: xai_tech_promtail
    volumes:
      - ./grafana/promtail-config.yaml:/etc/promtail/config.yml
      - /var/log:/var/log
      - ./logs:/var/log/app
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.0.0
    container_name: xai_tech_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    depends_on:
      - loki

  # backend:
  #   build: .
  #   container_name: xai_tech_backend
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     DATABASE_URL: postgresql://user:password@postgres:5432/xai_tech
  #     JWT_SECRET: your-super-secret-key
  #     PORT: 4000
  #     NODE_ENV: development
  #   volumes:
  #     - ./logs:/app/logs
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

volumes:
  postgres_data:
  grafana_data:
  loki_data:
